### PR TITLE
Add `allow_empty` to options

### PR DESCRIPTION
**Pull request by johnhorner**
See https://github.com/shlomif/perl-XML-RSS/issues/20

### CODE REVIEW

**Comment by shlomif** [comment]
@johnhorner : hi.

1. Can you add automated tests?

2. The new POD is bad

**Comment by shlomif** [comment]
@johnhorner : hi. you Missed explicitly adding the XML tags' angle brackets.

**Comment by johnhorner** [comment]
Test added, POD fixed.

**Comment by shlomif** [comment]
hi @johnhorner 

1. Please squash the commits.
2. Please replace `use constant` with regular `my $...` decls.
3. Avoid using `$_`.
4. Pass the new test through perltidy.
5. I recommend using git feature branches instead of "master"

**Comment by johnhorner** [comment]
Will do today but a  note on the constants, I just copied a similar test, `enclosures-multi.t`, I really don't know why constants are there in the first place.

**Pull request closed without merging**
